### ISSUE TITLE
entity.save gives me an error

### ISSUE THREAD

**Issue by Fernandobo21** [XRM-OSS/D365-UI-Test#10]
Hi,
First of all, thanks for sharing this implementation of Jest and D365. 
I'm starting to implement some tests and i'm stucked trying to save one registry.

After setting some values i¡m using the xrmTest.Entity.save(); (also tried xrmTest.Entity.save(true)) instruction to save the record and it returns me this error:
![image](https://user-images.githubusercontent.com/4930082/104947939-c3490b80-59bc-11eb-81e7-5c4135d1f84e.png)

Don't know what to do to save the record, is there any other way?

Many thanks agains for sharing this solution, in my opinion it's the best to create UI test over DataVerse, CDS or Dynamics.
Best regards.

**Comment by DigitalFlow** [comment]
Hi @Fernandobo21,

thanks for the kind words and for giving it a try.
For simple tests, you might also want to check out the chrome extension, which can help you in designing the tests: https://github.com/XRM-OSS/D365-UI-Test-Designer

As for your error: You most certainly have some required fields which are not filled out at the time where you want to save, can you check that?

Kind Regards,
Florian

**Comment by Fernandobo21** [comment]
wow! thanks for the really quick answer.

I'm totally using it for UI test in my pipelines and for the customers, with the chrome extension the QA tester can cooperate with the developers, in my case this implementation gives a plus for both , QA and DEV team. Big round of applause for sharing.

Your guess was correct. I'm trying to validate my javascript that makes some fields mandatory. 
there are two ways to check that:
1- Entity.save() and take a look at the notification errors.
2-  Check the fields if they are mandatory or not (with expect or something like that)

As always, i chose the problematic option, i have QA soul, jajaja.
If is not an issue, then i will close it and get the second option.

I've created the test with the extension, thats why i click the save button and then check the mandatory fields. I export the test from the extension.

Thanks again.
Fernando

**Comment by DigitalFlow** [comment]
Hi @Fernandobo21,

thanks for your feedback :)

In the upcoming releases I want to add a new assertion to the UI designer, which is "Assert Save fails".
This assertion would trigger the save function and expect it to fail. That would be ideal for your use case.

For the time being you have to chose the second approach that you described, in the UI Test designer you can just click the assertions button near the Actions label and then you can choose all fields that should be mandatory inside the dropdown that is added to the bottom of your test.

There you can check the checkbox before the "Required Level" label and select "Required", then the extension will generate code for all selected controls to be mandatory.

Please give it a try and come back to me if you're having problems. If it works as expected, please close the issue :)

Kind Regards,
Florian

**Comment by Fernandobo21** [comment]
Hi florian.

I'm really sorry.
I was my mistake the error of the save.

I've got in the afterall a Close so i didn't see the error. 
The error was that the user doesn't have provileges to save the registry with the value i put.

Sorry to make you lose your time.
Closing the ticket. 
State: closed.
Status Reason: Idiot.

Thanks again.

**Comment by DigitalFlow** [comment]
Hi @Fernandobo21,

no worries, thanks for the laugh :D

Kind Regards,
Florian
