### ISSUE TITLE
Grid and Tabs

### ISSUE THREAD

**Issue by imartinflores** [XRM-OSS/D365-UI-Test#13]
Hi! 

What I need to use to open a Tab or interact with SubGrid ? can I use an xpath ?
I've tried the id, aria-label, data-id and no luck.

"Cannot read property 'setDisplayState' of null"
This is one tab, as example:

<img width="635" alt="tabs" src="https://user-images.githubusercontent.com/17011557/106310628-c1543780-625b-11eb-85b0-2570c0e5f07f.PNG">

Thank you!

**Comment by DigitalFlow** [comment]
Hi @imartinflores, 

So far you can open tabs and check whether they are hidden or not, code tutorial: https://xrm-oss.github.io/D365-UI-Test/pages/Tutorials/07_Tabs.html


For subgrids there are currently functions for getting visibility, record count and opening a record by index: https://xrm-oss.github.io/D365-UI-Test/pages/Tutorials/06_Subgrids.html

note: For subgrid visibility, you can just use the XrmTest.Controls functions.
Creating records from Subgrids is not yet implemented, but it will be.

Did that help you?

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow , thanks!

Yes, thats really helpful, that is exactly what I have tried, but was not working with "tab3_4". I will give it a try in different ways.

1 more thing, I can probably push code if you want for this. I have noticed that during the login, we dont have the mfa option activated, and when I do not pass the mfa as a parameter to the open() method, it keeps waiting for the "remember button id", which we dont have:

if (handleRememberLogin && !extendedProperties.mfaSecret) {
                await this.dontRememberLogin();
            }
            
Can we put an option to avoid waiting for that remember button ?  
            
Thanks a lot!
Nacho

**Comment by imartinflores** [comment]
Hey, If I am not wrong, that PR should resolve the issue I mentioned above :) is that right ?

Thanks!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

yes this was a PR for on premise support, but it's not ready and I guess there are some things that I would do differently now.

I have an idea for handling the login in case no remember button appears, I'll commit it soon.

Are you using UCI in v8.2? As stated in the ReadMe, current plan is to drop RUI support and to focus on UCI, since RUI has been deprecated.

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow !

I am using Microsoft Dynamics 365 Online Version 9.1 (9.1) (DB 9.1) and I am using the UCI yes.

That sounds good!
Thanks!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

just released a patched version as v0.1.10.
Can you give it a try?

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow ! 

Definitely will give it a try and let you know!

Thanks!

**Comment by imartinflores** [comment]
Hi @DigitalFlow the login works good now for me, is not waiting for that element anymore, thanks for that!

I am gonna try finding that tab now :) 

Regards,
Nacho

**Comment by DigitalFlow** [comment]
Alright, please ping me once you're done :)

**Comment by imartinflores** [comment]
@DigitalFlow  everything is working good, just saw that the tabName on the form editor is similar to the data-id on my picture

"tab_RecentCases".  Is there any example on the repo to look on how to create an incident ? using the WebApiClient ?

**Comment by DigitalFlow** [comment]
@imartinflores 
Usually you would open a form, fill out the fields and save. 
Open Create Form: https://xrm-oss.github.io/D365-UI-Test/pages/Tutorials/02_Navigation.html#open-create-forms

You can also use the macro capture of the D365-UI-Test-Designer extension for recording this test:
https://github.com/XRM-OSS/D365-UI-Test-Designer

**Comment by imartinflores** [comment]
Yes, we usually use the OrganizationService to create records, since we need to create multiple of them in order to test, thats what I was thinking if there is any way of using the WebApiClient for this instead recreating all the journey through the UI.

Will give it a try by using the create form.

**Comment by DigitalFlow** [comment]
You could also use Xrm.WebApiClient if you want.
We have a function for finding the Xrm object on the page, unfortunately it is not yet exported from the library:

https://github.com/XRM-OSS/D365-UI-Test/blob/master/src/xrm/Global.ts

I might export it, but you should think the whole test structure through, usually you would not want to create records through the WebAPI on every run.

**Comment by imartinflores** [comment]
Thanks!

Is the Test Designer working ? Ive added the extension, but when I open it, Recording remains as "Inactive", and I cant select any entity or activate the Recording.

Thank you!

**Comment by DigitalFlow** [comment]
You need to create a test first, then you can select it in the dropdown beside the "Recording Inactive"

**Comment by imartinflores** [comment]
But when I click on "Add Test" the entity form is empty, even navigating to an Account or a Case form in CRM

**Comment by imartinflores** [comment]
<img width="381" alt="testdesigner" src="https://user-images.githubusercontent.com/17011557/106460164-cd720c00-648a-11eb-9e3f-9dcda4b3e159.PNG">

**Comment by DigitalFlow** [comment]
If you just installed it, you have to load the refresh the whole CRM page in your browser so that the extension scripts are loaded.
Afterwards, when navigating to a form and opening the extension, the entity should be listed in there.

Documentation and a getting started video for the extension are planned.

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

did it work out?

**Comment by imartinflores** [comment]
Hi @DigitalFlow  it worked after reloading, thanks! There are some actions I could not record. I will continue trying, may be is me just doing something wrong. Cant find some subgrids names, so I need to check that. Our CRM implementation is HUGE, so I have a lot of things to try ...

Thanks for helping!

**Comment by imartinflores** [comment]
Something I notice, when I open a contact, I create a new Test, then I set Recording Active, and I click on capture, but when I click on a Tab, its not tracking anything on the recorder, am I doing something wrong ?

**Comment by DigitalFlow** [comment]
It is only tracking setting of values inside fields right now. No actions are recorded yet for anything else.
This might get implemented in the future.

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

you initially tried to create records using the Web API.
With the release of v0.1.22 there is now a dedicated class for handling WebAPI access: `XrmUITest.WebApi` ([Docs](https://xrm-oss.github.io/D365-UI-Test/classes/webapi.html)).
You can give it a try if you want.

The initial issues regarding grids and tabs are probably solved, so I'll close this issue.
For feedback or further questions, please don't hesitate to reach out.

Kind regards,
Florian
