### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by imartinflores** [XRM-OSS/D365-UI-Test#18]
Hi @DigitalFlow ! Sorry to bother, just wondering what should I use as a "name" when  trying to retrieve the state for a Control ?

Should I use the name of the control in the solution customisation ?
Is the locator name ?

I am getting this error when trying:
const { isVisible, isDisabled } = await xrmTest.Control.get("win_leveloptionset");

Cannot read property 'getVisible' of null

Thanks!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

when you install the [levelup utility](https://chrome.google.com/webstore/detail/level-up-for-dynamics-365/bjnkkhimoaclnddigpphpgkfgeggokam?hl=de&gl=BE) into your chrome, then there is a plugin "Logical names" which shows you the control names for all controls and also the tab names for all tabs.

The names shown there are the ones to use.
The [D365-UI-Test Designer chrome extension](https://chrome.google.com/webstore/detail/d365-ui-test-designer/lfcoehhlodiaehjepemaogbgadfoipog?hl=de&gl=BE) can help you finding the correct names as well.

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Thanks @DigitalFlow  , that was my first try, but still getting the same error when using the name provided by Level Up 
Nacho

**Comment by imartinflores** [comment]
Nvm, even if I try with a control, still throwing the same:
page.evaluate: Evaluation failed: TypeError: Cannot read property 'getVisible' of null .

This is the control I am trying to interact with:

{"attributeType":"memo","controlName":"win_description","controlType":"standard","label":"Description","logicalName":"win_description","type":"control"}

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

same result when you create a new case by using 
> await xrmTest.Navigation.openCreateForm("incident");

instead of clicking the new button?

Kind Regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow , thanks for the suggestion, thats working perfectly fine seems like. I am thinking if it has something to do with the new tab, seems like when I change to focus on it, the xrmTest is not able to find the element, should I do something after bringing the new tab to the front ?

`
const [myCase] = await Promise.all([ context.waitForEvent('page'), 
await xrmTest.Button.click({ byLabel: "TestCase" }) ]) 
await myCase.waitForLoadState(); 
await myCase.bringToFront()
`

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

I can't exactly imagine what's happening when you click the button, usually the new form loads in the same tab.
Can you create a short video or gif of what's happening?

The instance of the xrmUiTest that you created has a reference to its page, which is readonly.
So when you open a new tab and use the xrmUiTest of your old one for doing stuff, it's using the old tab still.

Do you need to work with a new tab? For this I would probably need to make the `_page` property of the XrmUiTest class writable by providing a setter, so that you can switch tab contexts.

Does that sound good to you?

Kind regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow , I think that's it. Yes, in our product, when you click on the ribbon button to create a new incident, it does open a new tab in the browser. I think it's exactly what you've mentioned. I can try by creating a new instance of the XrmUiTest and at least check if it can finds the element to confirm. Anyways, I can also use what you suggested and that is completely fine, so thanks a ton for that, really appreciated!
