### ISSUE TITLE
WebApi Usage

### ISSUE THREAD

**Issue by imartinflores** [XRM-OSS/D365-UI-Test#19]
Hi @DigitalFlow  , thats a really good feature, I've installed the latest version and having this issue when trying to create a record, I guess I might be missing something, but never used it before:

await xrmTest.WebApi.createRecord("incident",data); => where data being:

data = {"some data"} 

page.evaluate: Evaluation failed: Objectpage.evaluate: Evaluation failed: Object

Do you have any suggestion what could I be missing ?

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

WebAPI is sometimes a little unintuitive because of the way lookups are handled.
You can find out quite a lot in the MS docs on it however: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/webapi/perform-operations-web-api

An example how to create an incident in your UI Test using it would be:

```JS
await xrmTest.WebApi.createRecord("incident", { title: "Test Incident", "customerid_account@odata.bind": "/accounts(8c106b65-9200-ea11-a811-000d3a218624)" })
```

Please try out and give me some feedback :)

Kind regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow ! Thanks.

Just tried it, and still showing the same error message:

Just in case, the version I am using is: "d365-ui-test": "^0.1.24"
![image](https://user-images.githubusercontent.com/17011557/126286229-7d074e53-cde1-46e7-b614-e76568a81e95.png)

Thanks!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

I just did a quick check and it works on my side.
When you open your CRM organization with your browser, open the developer console and paste the following code, do you get an error?

```JS
Xrm.WebApi.createRecord("incident", { title: "Test Incident", "customerid_account@odata.bind": "/accounts(SOME-ACCOUNT-ID)" }).then(console.dir, console.error);
```

It might be that you have custom plugins which fail if some data is missing. In that case you need to send the required data as well (and probably also fix your plugins).

Kind regards,
Florian

**Comment by imartinflores** [comment]
@DigitalFlow  thanks a lot, think we can close this. For some reason, the display name for contacts was account, quite confusing, but I changed:
customerid_account to customerid_contact and /contacts

its working fine now. Thanks a lot as always!

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

yeah that's one of the quirks of web api.
CustomerId is a polymorphic field, so it can point to different entities. It can point to accounts, but also to contacts.

In WebAPI polymorphic fields have a different navigation property name accordig to which entity you want to relate to.
So when you want to put in an account, you have to use customerid_account and an /accounts() value, but if you want to put in a contact, you have to use customerid_contact and /contacts() as value.

This is quite annoying to deal with and unintuitive, but that's how it's implemented in there...

Glad that it works for you now however :)
I'll close this for the time being.

Kind regards,
Florian
