### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by imartinflores** [XRM-OSS/D365-UI-Test#31]
Hi @DigitalFlow ! I Hope to not bother you. Is there any plan to merge or release more updates to the project soon? 
We would like to get more used to it to start contributing, if that is the case, is there any plan to release new versions and features more often ?
Thanks a lot, appreciate your help.

**Comment by DigitalFlow** [comment]
Hi @imartinflores,

yes sure :)

I was on vacation, sorry for not responding that fast.
I'll merge the PRs and update the package soon :)

Kind regards,
Florian

**Comment by imartinflores** [comment]
Hi @DigitalFlow  , thanks a lot!
Hope you had a really nice holidays!

Regards, 
Nacho
