### ISSUE TITLE
Cannot get ID of an entity record after second test attempt (Navigation error?)

### ISSUE THREAD

**Issue by julianYaman** [XRM-OSS/D365-UI-Test#38]
Hello, currently I have a really strange problem when trying to read values of an entity record (in my case the ID).

When I run the test for the first time, it returns the ID of the record without any problems (like it should usually do). After the first try, it no longer does.
It seems to me that any background process is preventing the `Entity.getId()` call from retrieving the ID. 

I assumed this after I also observed that after the timeout, the next test started and right after the start an error message appeared.
`Error: page.evaluate: Execution context was destroyed, most likely because of a navigation`

My code is actually very simple:
```js
Logger.info("Opening the entry"); // Will be logged
await xrmTest.Navigation.navigateTo({
  entityName: "entity",
  pageType: "entityrecord",
  entityId: "my-id"
})
Logger.debug("Opened the entry"); // Won't be logged; test will time out
const id = await xrmTest.Entity.getId();
Logger.debug(`Entry ID: ${id}`);
assert.equal(id, `{my-id}`);
```

(Additional observation: see https://github.com/XRM-OSS/D365-UI-Test/issues/38#issuecomment-1033598472)

What should I do?
Is there a workaround I can try?

**Comment by imartinflores** [comment]
Hi @julianYaman , if the context was destroyed, then the getId() will not work , since it tries to execute a WebApi function and the context + page will be null. 
Why the second attempt is running ? is your test failing on the first try ? does it open a new browser and xrmTest instance on your retry ?

**Comment by julianYaman** [comment]
I just started the whole test for a second time. In this second run, `.getId()` does not work anymore while it did in the first run.
After the second, it won't work anymore for an unknown amount of attempts. The error message appears after the test case timed out and the next test case (the next `it(...)`) started.

**Comment by julianYaman** [comment]
Now I observed that this might have something to do with the `Navigation.navigateTo()` function. I manually opened a record to see if I can find the source of the problem.

This is my code:
```js
Logger.info("Opening the entry"); // Will be logged
await xrmTest.Navigation.navigateTo({
  entityName: "entity",
  pageType: "entityrecord",
  entityId: "my-id"
})
Logger.debug("Opened the entry"); // Won't be logged; test will time out
const id = await xrmTest.Entity.getId();
Logger.debug(`Entry ID: ${id}`);
assert.equal(id, `{my-id}`);
```

I also updated the code in the issue.

**Comment by imartinflores** [comment]
I assume something is failing and preventing that function to get executed. What is the entity you are trying to open ?
Instead of navigateTo() , can you try openUpdateForm("entityName", "entityId") ?

**Comment by imartinflores** [comment]
Yeah, there might be something wrong in the navigation. This is working fine for me:

await xrmTest.Navigation.navigateTo({
            pageType: "entityrecord",
            entityName: "contact",
            entityId: "recordguid"
          })

**Comment by julianYaman** [comment]
Any idea where to start fixing this?

**Comment by imartinflores** [comment]
Hmm, sounds weird. I am just trying to reproduce it but I can't.  Is that navigation working at any point ? Does it navigate to your entity when running the test for the first time ?

**Comment by julianYaman** [comment]
Yes, and it actually navigates me to the entry every time I start the test. But it seems that the navigation does not "finish". The page loads normally with no problems or error messages, but then nothing happens.

**Comment by imartinflores** [comment]
I think what you can try doing is increasing the timeout on the XrmUITest.js class , give it more time to see if it loads properly and does something after it. If you can debug, step into the navigateTo and try to see where is failing ?

**Comment by julianYaman** [comment]
So I debugged and saw that the issue could be caused by the `xrmTest.waitForIdleness()` call in:
https://github.com/XRM-OSS/D365-UI-Test/blob/99b5e6abbbd7d7bec92e44e4f02f726fa96226cf/src/xrm/Navigation.ts#L104

A few tries later it actually worked again, and then again not for an unknown number of attempts.

I haven't found any specific reason why it is timing out sometimes and sometimes not. Maybe a Promise is not resolved correctly or there is any other unknown reason why it stays in this `do ... while` loop even when the site is fully loaded.
https://github.com/XRM-OSS/D365-UI-Test/blob/99b5e6abbbd7d7bec92e44e4f02f726fa96226cf/src/xrm/XrmUITest.ts#L336-L353

After that, I tried to `Navigation.openUpdateForm(...)` asynchronously but in sync with the code execution, followed by an asynchronous 'delay' function that I already built myself before.

```js
xrmTest.Navigation.openUpdateForm( // no 'await' call
    "entity",
    "my id"
);
Logger.info("Quick delay")
await wait(10); // wait 10 seconds
Logger.debug("Opened the entry");
const validationLog = await xrmTest.Attribute.getValue("validationlog");
Logger.debug(`Validation log: \n${validationLog}`);
```

Every test I run after using this workaround has returned the needed values successfully
Strange that I have to do this synchronously but as far as it helps to solve with my issue, it's fine with me 😄

**Comment by imartinflores** [comment]
Nice. If the problem is on the waitForIdleness, then something might be running on the back as you said that is not being resolved by that time or having some delays and that's probably why is timing out :) glad you worked it out!

**Comment by julianYaman** [comment]
Yes, I am glad I found this solution, because it would have prevented me from continuing with my current project 😄
Also thanks for the advice to debug my code, otherwise I would not have found out that it has something to do with `waitForIdleness`.

I may have also figured out that the problem could be related to using custom entities and custom functions in CRM. I can't really prove it, but it seems to make sense since I'm only having issues with this one entity. (also got problem when I tried to asynchronously save changes with `Entity.save()` which also contains an asynchronous `waitForIdleness` call)

I'm closing the issue then.
Thanks again 👍

**Comment by DigitalFlow** [comment]
HI @julianYaman,

glad that you found a solution and sorry I was not able to respond in time, last week has been a mess...
Also thanks @imartinflores for helping out, it's really appreciated 👍 

I have to warn though, by not using `await` with `openUpdateForm` you're not calling it synchronously, but just not waiting for any result (be it a success or failure).

If it is only on your custom entity, you might want to check whether some custom script is causing these issues. There might be some polling done inside the form scripts which resets the internal timer of the `waitForIdleness` call every time it runs, is that possible?

Kind regards,
Florian

**Comment by julianYaman** [comment]
Hello @DigitalFlow,

I will forward this to the other developers as I unfortunately don't have the insights there :-/

Currently, I'm trying my own "error handling" which, like you already mentioned, won't work perfectly because I do not really wait for the actual result.
