### ISSUE TITLE
Node version needs upgrading to 12 or higher in azure-pipelines.yml

### ISSUE THREAD

**Issue by jimiryquai** [XRM-OSS/D365-UI-Test#39]
npm install and build script fails with Node v10

**Comment by julianYaman** [comment]
In general, I can only recommend using the latest LTS version of Node.js (currently v16.14.0) to guarantee the best stability in executing your JS code.

**Comment by jimiryquai** [comment]
Yeah I was referring to the YAML here: https://xrm-oss.github.io/D365-UI-Test/pages/Tutorials/10_DevOps.html and then realised it's not even part of this repo after posting

**Comment by DigitalFlow** [comment]
Thanks for the input, I'll update the Tutorial page.

**Comment by DigitalFlow** [comment]
Documentation has been updated.
